.TH FFMPEGTHUMBNAILER 1
.SH NAME
ffmpegthumbnailer \- fast and lightweight video thumbnailer
.SH SYNOPSIS
.B ffmpegthumbnailer
[\fIoptions\fR]
.SH DESCRIPTION
.I  Ffmpegthumbnailer
is a lightweight video thumbnailer that can be used by file managers to create
thumbnails for your video files. The thumbnailer uses ffmpeg to decode frames
from the video files, so supported videoformats depend on the configuration
flags of ffmpeg.
.SH OPTIONS
.TP
\fB\-i\fR<s>
: input file
.TP
\fB\-o\fR<s>
: output file
.TP
\fB\-s\fR<n>
: thumbnail size (use 0 for original size) (default: 128)
.TP
\fB\-q\fR<n>
: image quality (0 = bad, 10 = best) (default: 8) (only for jpeg)
.TP
\fB\-c\fR<s>
: override image format (jpeg or png) (default: determined by filename)
.TP
\fB\-t\fR<n|s>
: time to seek to (percentage or absolute time hh:mm:ss) (default: 10%)
.TP
\fB\-a\fR
: ignore aspect ratio and generate square thumbnail
.TP

\fB\-f\fR
: create a movie strip overlay
.TP
\fB\-m\fR
: prefer embedded image metadata over video content
.TP
\fB\-h\fR
: display this help
.SH AUTHOR
Written by Dirk Vanden Boer.
.SH "REPORTING BUGS"
Report bugs to <http://code.google.com/p/ffmpegthumbnailer/issues/list>
.SH COPYRIGHT
Copyright \(co 2008 Dirk Vanden Boer <dirk.vdb@gmail.com>
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License (version 2 or later) <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
